#import "DollarDefaultGestures.h"
#import "DollarPointCloud.h"
#import "DollarPoint.h"

DollarPointCloud * MakePointCloud(NSString *name, NSArray *points) {
    return [[DollarPointCloud alloc] initWithName:name points:points];
}

DollarPoint * MakePoint(float x, float y, int id) {
    return [[DollarPoint alloc] initWithId:@(id) x:x y:y];
}

@implementation DollarDefaultGestures

+ (id)defaultPointClouds {
    static NSArray *defaultPointClouds = nil;
    if (!defaultPointClouds) {
        defaultPointClouds = [self pointClouds];
    }
    return defaultPointClouds;
}

+ (NSMutableArray *)pointClouds {
    NSMutableArray *pointClouds = [NSMutableArray array];
   	
    // Alphabetic Gesture
    
    pointClouds[0] = MakePointCloud(@"Fontfamily_T_Gesture", @[
                                                               MakePoint(30,7,1),
                                                               MakePoint(103,7,1),
                                                               
                                                               MakePoint(66,7,2),
                                                               MakePoint(66,87,2)
                                                               ]);
    
    pointClouds[1] = MakePointCloud(@"Selectall_A_Gesture", @[
                                                              MakePoint(62 ,412,1),
                                                              MakePoint(62 ,405,1),
                                                              MakePoint(64 ,396,1),
                                                              MakePoint(67 ,384,1),
                                                              MakePoint(71 ,371,1),
                                                              MakePoint(75 ,359,1),
                                                              MakePoint(80 ,345,1),
                                                              MakePoint(84 ,331,1),
                                                              MakePoint(88 ,316,1),
                                                              MakePoint(92 ,299,1),
                                                              MakePoint(95 ,282,1),
                                                              MakePoint(98 ,264,1),
                                                              MakePoint(102 ,247,1),
                                                              MakePoint(106 ,230,1),
                                                              MakePoint(110 ,214,1),
                                                              MakePoint(115 ,198,1),
                                                              MakePoint(119 ,183,1),
                                                              MakePoint(123 ,170,1),
                                                              MakePoint(125 ,161,1),
                                                              MakePoint(128 ,151,1),
                                                              MakePoint(130 ,143,1),
                                                              MakePoint(132 ,137,1),
                                                              MakePoint(135 ,128,1),
                                                              MakePoint(136 ,126,1),
                                                              MakePoint(136 ,123,1),
                                                              MakePoint(137 ,122,1),
                                                              MakePoint(137 ,122,1),
                                                              MakePoint(138 ,122,1),
                                                              MakePoint(139 ,122,1),
                                                              MakePoint(141 ,125,1),
                                                              MakePoint(145 ,130,1),
                                                              MakePoint(149 ,137,1),
                                                              MakePoint(154 ,146,1),
                                                              MakePoint(159 ,156,1),
                                                              MakePoint(165 ,168,1),
                                                              MakePoint(171 ,180,1),
                                                              MakePoint(177 ,190,1),
                                                              MakePoint(182 ,203,1),
                                                              MakePoint(187 ,215,1),
                                                              MakePoint(191 ,227,1),
                                                              MakePoint(196 ,241,1),
                                                              MakePoint(201 ,253,1),
                                                              MakePoint(205 ,265,1),
                                                              MakePoint(210 ,276,1),
                                                              MakePoint(214 ,287,1),
                                                              MakePoint(217 ,297,1),
                                                              MakePoint(220 ,308,1),
                                                              MakePoint(222 ,319,1),
                                                              MakePoint(224 ,330,1),
                                                              MakePoint(226 ,340,1),
                                                              MakePoint(228 ,351,1),
                                                              MakePoint(230 ,360,1),
                                                              MakePoint(231 ,368,1),
                                                              MakePoint(233 ,377,1),
                                                              MakePoint(235 ,385,1),
                                                              MakePoint(236 ,393,1),
                                                              MakePoint(237 ,399,1),
                                                              MakePoint(238 ,405,1),
                                                              MakePoint(239 ,410,1),
                                                              MakePoint(240 ,414,1),
                                                              MakePoint(240 ,418,1),
                                                              MakePoint(241 ,421,1),
                                                              MakePoint(242 ,424,1),
                                                              MakePoint(242 ,427,1),
                                                              MakePoint(243 ,428,1),
                                                              MakePoint(244 ,430,1),
                                                              MakePoint(244 ,431,1),
                                                              MakePoint(245 ,432,1),
                                                              MakePoint(245 ,432,1),
                                                              MakePoint(245 ,433,1),
                                                              MakePoint(245 ,434,1),
                                                              MakePoint(246 ,434,1),
                                                              MakePoint(96 ,280,2),
                                                              MakePoint(101 ,278,2),
                                                              MakePoint(109 ,276,2),
                                                              MakePoint(118 ,274,2),
                                                              MakePoint(128 ,272,2),
                                                              MakePoint(142 ,270,2),
                                                              MakePoint(153 ,267,2),
                                                              MakePoint(166 ,264,2),
                                                              MakePoint(178 ,262,2),
                                                              MakePoint(186 ,259,2),
                                                              MakePoint(193 ,258,2),
                                                              MakePoint(199 ,256,2),
                                                              MakePoint(204 ,255,2),
                                                              MakePoint(207 ,255,2),
                                                              MakePoint(209 ,255,2),
                                                              MakePoint(210 ,255,2),
                                                              MakePoint(212 ,255,2),
                                                              MakePoint(212 ,255,2),
                                                              MakePoint(213 ,255,2),
                                                              MakePoint(213 ,255,2),
                                                              MakePoint(214 ,255,2),
                                                              MakePoint(215 ,255,2),
                                                              MakePoint(216 ,255,2),
                                                              MakePoint(216 ,255,2),
                                                              MakePoint(217 ,255,2),
                                                              MakePoint(217 ,255,2),
                                                              MakePoint(218 ,255,2),
                                                              MakePoint(220 ,255,2),
                                                              MakePoint(221 ,255,2),
                                                              MakePoint(223 ,254,2),
                                                              MakePoint(224 ,254,2),
                                                              MakePoint(225 ,254,2),
                                                              MakePoint(226 ,254,2),
                                                              MakePoint(226 ,254,2),
                                                              MakePoint(227 ,254,2),
                                                              MakePoint(228 ,254,2),
                                                              MakePoint(229 ,254,2),
                                                              MakePoint(230 ,254,2),
                                                              MakePoint(231 ,254,2),
                                                              MakePoint(231 ,254,2),
                                                              MakePoint(232 ,254,2),
                                                              MakePoint(232 ,254,2),
                                                              ]
                                    );
    
    
    pointClouds[2] = MakePointCloud(@"Delete_D_Gesture", @[
                                            MakePoint(102 ,163,1),
                                            MakePoint(102 ,168,1),
                                            MakePoint(102 ,176,1),
                                            MakePoint(102 ,188,1),
                                            MakePoint(102 ,203,1),
                                            MakePoint(100 ,219,1),
                                            MakePoint(100 ,237,1),
                                            MakePoint(100 ,256,1),
                                            MakePoint(100 ,274,1),
                                            MakePoint(100 ,291,1),
                                            MakePoint(100 ,308,1),
                                            MakePoint(102 ,324,1),
                                            MakePoint(103 ,339,1),
                                            MakePoint(104 ,352,1),
                                            MakePoint(105 ,364,1),
                                            MakePoint(105 ,373,1),
                                            MakePoint(105 ,382,1),
                                            MakePoint(105 ,389,1),
                                            MakePoint(105 ,393,1),
                                            MakePoint(105 ,396,1),
                                            MakePoint(105 ,396,1),
                                            MakePoint(37 ,179,2),
                                            MakePoint(40 ,179,2),
                                            MakePoint(47 ,176,2),
                                            MakePoint(53 ,174,2),
                                            MakePoint(60 ,171,2),
                                            MakePoint(69 ,168,2),
                                            MakePoint(76 ,166,2),
                                            MakePoint(84 ,164,2),
                                            MakePoint(90 ,162,2),
                                            MakePoint(97 ,161,2),
                                            MakePoint(104 ,160,2),
                                            MakePoint(110 ,160,2),
                                            MakePoint(117 ,159,2),
                                            MakePoint(123 ,159,2),
                                            MakePoint(128 ,159,2),
                                            MakePoint(134 ,159,2),
                                            MakePoint(139 ,159,2),
                                            MakePoint(145 ,159,2),
                                            MakePoint(150 ,159,2),
                                            MakePoint(155 ,160,2),
                                            MakePoint(159 ,161,2),
                                            MakePoint(163 ,163,2),
                                            MakePoint(168 ,164,2),
                                            MakePoint(173 ,167,2),
                                            MakePoint(178 ,169,2),
                                            MakePoint(183 ,171,2),
                                            MakePoint(188 ,173,2),
                                            MakePoint(192 ,175,2),
                                            MakePoint(198 ,178,2),
                                            MakePoint(203 ,181,2),
                                            MakePoint(209 ,184,2),
                                            MakePoint(215 ,187,2),
                                            MakePoint(221 ,190,2),
                                            MakePoint(225 ,193,2),
                                            MakePoint(231 ,197,2),
                                            MakePoint(236 ,200,2),
                                            MakePoint(242 ,204,2),
                                            MakePoint(247 ,208,2),
                                            MakePoint(252 ,211,2),
                                            MakePoint(257 ,215,2),
                                            MakePoint(261 ,220,2),
                                            MakePoint(264 ,224,2),
                                            MakePoint(267 ,230,2),
                                            MakePoint(271 ,235,2),
                                            MakePoint(275 ,240,2),
                                            MakePoint(279 ,245,2),
                                            MakePoint(282 ,251,2),
                                            MakePoint(286 ,257,2),
                                            MakePoint(289 ,263,2),
                                            MakePoint(291 ,269,2),
                                            MakePoint(293 ,276,2),
                                            MakePoint(293 ,282,2),
                                            MakePoint(294 ,289,2),
                                            MakePoint(294 ,296,2),
                                            MakePoint(294 ,304,2),
                                            MakePoint(293 ,311,2),
                                            MakePoint(291 ,318,2),
                                            MakePoint(288 ,324,2),
                                            MakePoint(285 ,330,2),
                                            MakePoint(282 ,335,2),
                                            MakePoint(279 ,340,2),
                                            MakePoint(276 ,346,2),
                                            MakePoint(274 ,351,2),
                                            MakePoint(271 ,355,2),
                                            MakePoint(267 ,360,2),
                                            MakePoint(264 ,365,2),
                                            MakePoint(261 ,369,2),
                                            MakePoint(258 ,372,2),
                                            MakePoint(255 ,375,2),
                                            MakePoint(250 ,378,2),
                                            MakePoint(246 ,381,2),
                                            MakePoint(242 ,383,2),
                                            MakePoint(237 ,384,2),
                                            MakePoint(232 ,386,2),
                                            MakePoint(227 ,387,2),
                                            MakePoint(221 ,389,2),
                                            MakePoint(216 ,390,2),
                                            MakePoint(209 ,391,2),
                                            MakePoint(203 ,392,2),
                                            MakePoint(196 ,394,2),
                                            MakePoint(189 ,395,2),
                                            MakePoint(182 ,396,2),
                                            MakePoint(174 ,398,2),
                                            MakePoint(167 ,399,2),
                                            MakePoint(161 ,400,2),
                                            MakePoint(155 ,401,2),
                                            MakePoint(148 ,402,2),
                                            MakePoint(141 ,403,2),
                                            MakePoint(135 ,403,2),
                                            MakePoint(129 ,404,2),
                                            MakePoint(122 ,404,2),
                                            MakePoint(116 ,404,2),
                                            MakePoint(108 ,404,2),
                                            MakePoint(102 ,404,2),
                                            MakePoint(97 ,404,2),
                                            MakePoint(92 ,404,2),
                                            MakePoint(87 ,402,2),
                                            MakePoint(83 ,401,2),
                                            MakePoint(78 ,400,2),
                                            MakePoint(74 ,398,2),
                                            MakePoint(71 ,396,2),
                                            MakePoint(67 ,395,2),
                                            MakePoint(63 ,393,2),
                                            MakePoint(60 ,391,2),
                                            MakePoint(56 ,389,2),
                                            MakePoint(52 ,387,2),
                                            MakePoint(49 ,386,2),
                                            MakePoint(45 ,384,2),
                                            MakePoint(42 ,383,2),
                                            MakePoint(40 ,382,2),
                                            MakePoint(38 ,380,2),
                                            MakePoint(37 ,379,2),
                                            MakePoint(36 ,378,2),
                                            MakePoint(35 ,378,2),
                                            MakePoint(35 ,377,2),
                                            MakePoint(35 ,377,2)
                                            ]);
    
    
    
    pointClouds[3] = MakePointCloud(@"Fontsize_P_Gesture", @[
                                                             MakePoint(507,8,1),
                                                             MakePoint(507,87,1),
                                                             
                                                             MakePoint(513,7,2),
                                                             MakePoint(528,7,2),
                                                             MakePoint(537,8,2),
                                                             MakePoint(544,10,2),
                                                             MakePoint(550,12,2),
                                                             MakePoint(555,15,2),
                                                             MakePoint(558,18,2),
                                                             MakePoint(560,22,2),
                                                             MakePoint(561,27,2),
                                                             MakePoint(562,33,2),
                                                             MakePoint(561,37,2),
                                                             MakePoint(559,42,2),
                                                             MakePoint(556,45,2),
                                                             MakePoint(550,48,2),
                                                             MakePoint(544,51,2),
                                                             MakePoint(538,53,2),
                                                             MakePoint(532,54,2),
                                                             MakePoint(525,55,2),
                                                             MakePoint(519,55,2),
                                                             MakePoint(513,55,2),
                                                             MakePoint(510,55,2)
                                                             ]);
    
    pointClouds[4] = MakePointCloud(@"Cut_X_Gesture", @[
                                            MakePoint(30,146,1),
                                            MakePoint(106,222,1),
                                            
                                            MakePoint(30,225,2),
                                            MakePoint(106,146,2)
                                            ]);
    
    pointClouds[5] = MakePointCloud(@"Highlight_H_Gesture", @[
                                                              MakePoint(188,137,1),
                                                              MakePoint(188,225,1),
                                                              
                                                              MakePoint(188,180,2),
                                                              MakePoint(241,180,2),
                                                              
                                                              MakePoint(241,137,3),
                                                              MakePoint(241,225,3)
                                                              ]);
    
    pointClouds[6] = MakePointCloud(@"Italic_I_Gesture", @[
                                                           MakePoint(209,57,1),
                                                           MakePoint(213,57,1),
                                                           MakePoint(217,57,1),
                                                           MakePoint(223,57,1),
                                                           MakePoint(231,57,1),
                                                           MakePoint(236,56,1),
                                                           MakePoint(244,56,1),
                                                           MakePoint(251,55,1),
                                                           MakePoint(258,54,1),
                                                           MakePoint(265,54,1),
                                                           MakePoint(272,53,1),
                                                           MakePoint(278,52,1),
                                                           MakePoint(284,52,1),
                                                           MakePoint(289,51,1),
                                                           MakePoint(293,51,1),
                                                           MakePoint(296,50,1),
                                                           MakePoint(298,49,1),
                                                           MakePoint(300,49,1),
                                                           MakePoint(256,60,2),
                                                           MakePoint(256,62,2),
                                                           MakePoint(257,65,2),
                                                           MakePoint(257,70,2),
                                                           MakePoint(258,74,2),
                                                           MakePoint(258,79,2),
                                                           MakePoint(259,84,2),
                                                           MakePoint(260,90,2),
                                                           MakePoint(261,97,2),
                                                           MakePoint(262,104,2),
                                                           MakePoint(263,111,2),
                                                           MakePoint(264,118,2),
                                                           MakePoint(265,125,2),
                                                           MakePoint(267,133,2),
                                                           MakePoint(268,140,2),
                                                           MakePoint(270,147,2),
                                                           MakePoint(271,154,2),
                                                           MakePoint(272,160,2),
                                                           MakePoint(273,166,2),
                                                           MakePoint(273,172,2),
                                                           MakePoint(274,178,2),
                                                           MakePoint(274,184,2),
                                                           MakePoint(274,189,2),
                                                           MakePoint(274,195,2),
                                                           MakePoint(274,199,2),
                                                           MakePoint(274,203,2),
                                                           MakePoint(274,205,2),
                                                           MakePoint(274,207,2),
                                                           MakePoint(274,209,2),
                                                           MakePoint(274,210,2),
                                                           MakePoint(274,212,2),
                                                           MakePoint(274,214,2),
                                                           MakePoint(274,215,2),
                                                           MakePoint(274,216,2),
                                                           MakePoint(274,217,2),
                                                           MakePoint(274,218,2),
                                                           MakePoint(275,219,2),
                                                           MakePoint(275,221,2),
                                                           MakePoint(276,222,2),
                                                           MakePoint(276,223,2),
                                                           MakePoint(276,224,2),
                                                           MakePoint(276,225,2),
                                                           MakePoint(277,225,2),
                                                           MakePoint(245,234,3),
                                                           MakePoint(248,234,3),
                                                           MakePoint(249,234,3),
                                                           MakePoint(252,233,3),
                                                           MakePoint(255,232,3),
                                                           MakePoint(258,232,3),
                                                           MakePoint(262,231,3),
                                                           MakePoint(265,230,3),
                                                           MakePoint(269,229,3),
                                                           MakePoint(272,229,3),
                                                           MakePoint(276,228,3),
                                                           MakePoint(280,228,3),
                                                           MakePoint(283,227,3),
                                                           MakePoint(286,227,3),
                                                           MakePoint(289,226,3),
                                                           MakePoint(292,226,3),
                                                           MakePoint(296,225,3),
                                                           MakePoint(298,225,3),
                                                           MakePoint(301,224,3),
                                                           MakePoint(304,224,3),
                                                           MakePoint(306,224,3),
                                                           MakePoint(308,224,3),
                                                           MakePoint(311,223,3),
                                                           MakePoint(313,223,3),
                                                           MakePoint(316,223,3),
                                                           MakePoint(319,223,3),
                                                           MakePoint(321,222,3),
                                                           MakePoint(324,222,3),
                                                           MakePoint(326,222,3),
                                                           MakePoint(329,221,3),
                                                           MakePoint(331,221,3),
                                                           MakePoint(332,221,3),
                                                           MakePoint(333,221,3),
                                                           MakePoint(334,220,3)
                                                           ]);
    
    
    
    pointClouds[7] = MakePointCloud(@"Copy_C_Gesture", @[
                                                         MakePoint(224,162,1),
                                                         MakePoint(222 ,159,1),
                                                         MakePoint(211 ,157,1),
                                                         MakePoint(198 ,155,1),
                                                         MakePoint(173 ,154,1),
                                                         MakePoint(131 ,154,1),
                                                         MakePoint(118 ,157,1),
                                                         MakePoint(108 ,168,1),
                                                         MakePoint(95 ,199,1),
                                                         MakePoint(87 ,219,1),
                                                         MakePoint(84 ,253,1),
                                                         MakePoint(84 ,269,1),
                                                         MakePoint(84 ,286,1),
                                                         MakePoint(85 ,310,1),
                                                         MakePoint(87 ,320,1),
                                                         MakePoint(91 ,330,1),
                                                         MakePoint(95 ,339,1),
                                                         MakePoint(98 ,343,1),
                                                         MakePoint(106 ,350,1),
                                                         MakePoint(121 ,362,1),
                                                         MakePoint(130 ,367,1),
                                                         MakePoint(141 ,371,1),
                                                         MakePoint(150 ,372,1),
                                                         MakePoint(159 ,372,1),
                                                         MakePoint(170 ,372,1),
                                                         MakePoint(183 ,372,1),
                                                         MakePoint(192 ,372,1),
                                                         MakePoint(195 ,372,1),
                                                         MakePoint(196 ,371,1),
                                                         MakePoint(199 ,371,1),
                                                         MakePoint(200 ,370,1),
                                                         MakePoint(201 ,370,1),
                                                         MakePoint(201 ,369,1),
                                                         MakePoint(203 ,369,1),
                                                         MakePoint(204 ,369,1),
                                                         MakePoint(205 ,368,1),
                                                         MakePoint(207 ,367,1),
                                                         MakePoint(213 ,367,1),
                                                         MakePoint(216 ,367,1),
                                                         MakePoint(218 ,367,1),
                                                         MakePoint(219 ,367,1),
                                                         MakePoint(221 ,367,1),
                                                         MakePoint(221 ,365,1),
                                                         MakePoint(222 ,365,1)
                                                         ]);
    
    
    pointClouds [8] = MakePointCloud(@"Redo_Y_Gesture", @[
                                              
                                                          
                                                          
                                              
                                              MakePoint(259, 143,1),
                                              MakePoint(259, 148,1),
                                              MakePoint(260, 154,1),
                                              MakePoint(261, 162,1),
                                              MakePoint(265, 171,1),
                                              MakePoint(269, 178,1),
                                              MakePoint(274, 184,1),
                                              MakePoint(281, 187,1),
                                              MakePoint(286, 189,1),
                                              MakePoint(291, 189,1),
                                              MakePoint(297, 187,1),
                                              MakePoint(301, 181,1),
                                              MakePoint(305, 173,1),
                                              MakePoint(308, 164,1),
                                              MakePoint(310, 158,1),
                                              MakePoint(311, 153,1),
                                              MakePoint(311, 149,1),
                                              MakePoint(311, 146,1),
                                              MakePoint(311, 144,1),
                                              MakePoint(311 ,143,1),
                                              MakePoint(311 ,145,1),
                                              MakePoint(311, 148,1),
                                              MakePoint(312, 152,1),
                                              MakePoint(313, 156,1),
                                              MakePoint(314, 162,1),
                                              MakePoint(315, 168,1),
                                              MakePoint(316, 174,1),
                                              MakePoint(317, 181,1),
                                              MakePoint(318, 187,1),
                                              MakePoint(319, 194,1),
                                              MakePoint(320, 201,1),
                                              MakePoint(321, 208,1),
                                              MakePoint(322, 214,1),
                                              MakePoint(323, 219,1),
                                              MakePoint(324, 224,1),
                                              MakePoint(324, 229,1),
                                              MakePoint(324, 232,1),
                                              MakePoint(324, 235,1),
                                              MakePoint(324, 238,1),
                                              MakePoint(323, 240,1),
                                              MakePoint(321, 243,1),
                                              MakePoint(319, 245,1),
                                              MakePoint(316, 248,1),
                                              MakePoint(314, 249,1),
                                              MakePoint(311, 250,1),
                                              MakePoint(308, 251,1),
                                              MakePoint(304, 251,1),
                                              MakePoint(300, 251,1),
                                              MakePoint(296, 251,1),
                                              MakePoint(292, 250,1),
                                              MakePoint(289, 247,1),
                                              MakePoint(286, 245,1),
                                              MakePoint(283, 243,1),
                                              MakePoint(280, 241,1),
                                              MakePoint(277, 239,1),
                                              MakePoint(275, 237,1),
                                              MakePoint(273, 234,1),
                                              MakePoint(272, 231,1),
                                              MakePoint(271, 228,1),
                                              MakePoint(270, 226,1),
                                              MakePoint(270, 224,1),
                                              MakePoint(269, 223,1),
                                              MakePoint(269, 222,1),
                                              MakePoint(269, 223,1)
                                             
                                              
                                              ]);
    
    pointClouds[9] = MakePointCloud(@"Paste_V_Gesture", @[
                                                          MakePoint(140,90,1),
                                                          MakePoint(142,92,1),
                                                          MakePoint(143,94,1),
                                                          MakePoint(145,97,1),
                                                          MakePoint(148,101,1),
                                                          MakePoint(151,105,1),
                                                          MakePoint(154,111,1),
                                                          MakePoint(158,117,1),
                                                          MakePoint(162,123,1),
                                                          MakePoint(167,131,1),
                                                          MakePoint(172,138,1),
                                                          MakePoint(176,146,1),
                                                          MakePoint(182,153,1),
                                                          MakePoint(186,161,1),
                                                          MakePoint(191,168,1),
                                                          MakePoint(197,175,1),
                                                          MakePoint(202,181,1),
                                                          MakePoint(207,187,1),
                                                          MakePoint(213,195,1),
                                                          MakePoint(218,202,1),
                                                          MakePoint(221,207,1),
                                                          MakePoint(226,214,1),
                                                          MakePoint(229,219,1),
                                                          MakePoint(233,224,1),
                                                          MakePoint(236,229,1),
                                                          MakePoint(239,233,1),
                                                          MakePoint(242,237,1),
                                                          MakePoint(245,240,1),
                                                          MakePoint(248,243,1),
                                                          MakePoint(251,246,1),
                                                          MakePoint(253,248,1),
                                                          MakePoint(254,250,1),
                                                          MakePoint(256,252,1),
                                                          MakePoint(256,253,1),
                                                          MakePoint(257,254,1),
                                                          MakePoint(258,254,1),
                                                          MakePoint(259,253,1),
                                                          MakePoint(260,251,1),
                                                          MakePoint(261,250,1),
                                                          MakePoint(262,248,1),
                                                          MakePoint(263,246,1),
                                                          MakePoint(265,244,1),
                                                          MakePoint(266,241,1),
                                                          MakePoint(268,237,1),
                                                          MakePoint(271,233,1),
                                                          MakePoint(273,228,1),
                                                          MakePoint(275,224,1),
                                                          MakePoint(277,219,1),
                                                          MakePoint(279,215,1),
                                                          MakePoint(281,210,1),
                                                          MakePoint(283,206,1),
                                                          MakePoint(284,202,1),
                                                          MakePoint(285,199,1),
                                                          MakePoint(287,194,1),
                                                          MakePoint(288,190,1),
                                                          MakePoint(290,185,1),
                                                          MakePoint(291,180,1),
                                                          MakePoint(293,176,1),
                                                          MakePoint(294,172,1),
                                                          MakePoint(296,168,1),
                                                          MakePoint(297,164,1),
                                                          MakePoint(298,161,1),
                                                          MakePoint(299,157,1),
                                                          MakePoint(301,153,1),
                                                          MakePoint(302,148,1),
                                                          MakePoint(304,144,1),
                                                          MakePoint(305,141,1),
                                                          MakePoint(307,138,1),
                                                          MakePoint(309,134,1),
                                                          MakePoint(310,131,1),
                                                          MakePoint(312,127,1),
                                                          MakePoint(313,124,1),
                                                          MakePoint(314,120,1),
                                                          MakePoint(316,117,1),
                                                          MakePoint(318,114,1),
                                                          MakePoint(318,111,1),
                                                          MakePoint(319,109,1),
                                                          MakePoint(320,106,1),
                                                          MakePoint(321,104,1),
                                                          MakePoint(322,102,1),
                                                          MakePoint(323,99,1),
                                                          MakePoint(323,97,1),
                                                          MakePoint(324,95,1),
                                                          MakePoint(325,93,1),
                                                          MakePoint(325,91,1),
                                                          MakePoint(326,90,1),
                                                          MakePoint(326,88,1),
                                                          MakePoint(327,86,1),
                                                          MakePoint(327,85,1),
                                                          MakePoint(328,83,1),
                                                          MakePoint(328,82,1),
                                                          MakePoint(328,81,1),
                                                          MakePoint(329,79,1),
                                                          MakePoint(329,78,1),
                                                          MakePoint(329,77,1),
                                                          MakePoint(329,76,1),
                                                          MakePoint(329,75,1),
                                                          MakePoint(329,74,1)
                                                          ]);
    
    
    pointClouds[10] = MakePointCloud(@"Undo_Z_Gesture", @[
                                             
                                             
                                             
                                                                                
                                             
                                             
                                             MakePoint(186,148,1),
                                             MakePoint(192, 148,1),
                                             MakePoint(206, 146,1),
                                             MakePoint(225 ,142,1),
                                             MakePoint(248 ,137,1),
                                             MakePoint(272 ,132,1),
                                             MakePoint(296 ,128,1),
                                             MakePoint(317 ,124,1),
                                             MakePoint(334 ,121,1),
                                             MakePoint(345 ,118,1),
                                             MakePoint(353, 116,1),
                                             MakePoint(357 ,114,1),
                                             MakePoint(359, 114,1),
                                             MakePoint(358, 114,1),
                                             MakePoint(354, 118,1),
                                             MakePoint(349, 123,1),
                                             MakePoint(340, 130,1),
                                             MakePoint(329 ,140,1),
                                             MakePoint(315 ,153,1),
                                             MakePoint(299 ,166,1),
                                             MakePoint(282 ,180,1),
                                             MakePoint(266 ,194,1),
                                             MakePoint(250 ,207,1),
                                             MakePoint(235 ,218,1),
                                             MakePoint(221 ,228,1),
                                             MakePoint(209 ,236,1),
                                             MakePoint(201 ,241,1),
                                             MakePoint(196 ,243,1),
                                             MakePoint(194 ,245,1),
                                             MakePoint(193 ,245,1),
                                             MakePoint(193 ,246,1),
                                             MakePoint(194 ,246,1),
                                             MakePoint(200 ,244,1),
                                             MakePoint(210 ,242,1),
                                             MakePoint(226 ,239,1),
                                             MakePoint(242 ,235,1),
                                             MakePoint(260 ,230,1),
                                             MakePoint(280 ,226,1),
                                             MakePoint(299 ,222,1),
                                             MakePoint(318 ,218,1),
                                             MakePoint(334 ,215,1),
                                             MakePoint(349 ,212,1),
                                             MakePoint(359 ,210,1),
                                             MakePoint(367 ,209,1),
                                             MakePoint(373 ,208,1),
                                             MakePoint(379 ,206,1),
                                             MakePoint(383 ,205,1),
                                             MakePoint(386 ,205,1),
                                             MakePoint(388 ,204,1),
                                             MakePoint(389 ,203,1),
                                             MakePoint(390 ,203,1)

                                             
                                             ]);
    pointClouds[11] = MakePointCloud(@"Bold_B_Gesture", @[
                                                          
                                                          
                                            MakePoint(94 ,171,1),
                                            MakePoint(94 ,176,1),
                                            MakePoint(94 ,191,1),
                                            MakePoint(94 ,217,1),
                                            MakePoint(94 ,243,1),
                                            MakePoint(94 ,269,1),
                                            MakePoint(94 ,293,1),
                                            MakePoint(94 ,310,1),
                                            MakePoint(94 ,320,1),
                                            MakePoint(94 ,327,1),
                                            MakePoint(94 ,346,1),
                                            MakePoint(94 ,352,1),
                                            MakePoint(94 ,359,1),
                                            MakePoint(94 ,366,1),
                                            MakePoint(94 ,367,1),
                                            MakePoint(94 ,369,1),
                                            MakePoint(94 ,370,1),
                                            MakePoint(94 ,371,1),
                                            MakePoint(94 ,374,1),
                                            MakePoint(94 ,375,1),
                                            MakePoint(94 ,376,1),
                                            MakePoint(94 ,378,1),
                                            MakePoint(94 ,380,1),
                                            MakePoint(95 ,381,1),
                                            MakePoint(95 ,382,1),
                                            MakePoint(104 ,164,2),
                                            MakePoint(108 ,164,2),
                                            MakePoint(129 ,164,2),
                                            MakePoint(141 ,165,2),
                                            MakePoint(151 ,166,2),
                                            MakePoint(157 ,169,2),
                                            MakePoint(162 ,176,2),
                                            MakePoint(164 ,180,2),
                                            MakePoint(166 ,186,2),
                                            MakePoint(167 ,190,2),
                                            MakePoint(168 ,196,2),
                                            MakePoint(169 ,203,2),
                                            MakePoint(169 ,209,2),
                                            MakePoint(169 ,215,2),
                                            MakePoint(169 ,222,2),
                                            MakePoint(169 ,226,2),
                                            MakePoint(168 ,229,2),
                                            MakePoint(167 ,234,2),
                                            MakePoint(163 ,242,2),
                                            MakePoint(155 ,249,2),
                                            MakePoint(147 ,256,2),
                                            MakePoint(142 ,262,2),
                                            MakePoint(136 ,266,2),
                                            MakePoint(132 ,269,2),
                                            MakePoint(130 ,271,2),
                                            MakePoint(128 ,272,2),
                                            MakePoint(125 ,273,2),
                                            MakePoint(122 ,275,2),
                                            MakePoint(119 ,276,2),
                                            MakePoint(114 ,278,2),
                                            MakePoint(112 ,279,2),
                                            MakePoint(110 ,279,2),
                                            MakePoint(110 ,280,2),
                                            MakePoint(109 ,280,2),
                                            MakePoint(108 ,281,2),
                                            MakePoint(107 ,282,2),
                                            MakePoint(106 ,282,2),
                                            MakePoint(106 ,282,2),
                                            MakePoint(105 ,282,2),
                                            MakePoint(104 ,282,2),
                                            MakePoint(104 ,283,2),
                                            MakePoint(103 ,283,2),
                                            MakePoint(102 ,283,2),
                                            MakePoint(102 ,284,2),
                                            MakePoint(101 ,284,2),
                                            MakePoint(100 ,284,2),
                                            MakePoint(98 ,285,2),
                                            MakePoint(97 ,285,2),
                                            MakePoint(96 ,286,2),
                                            MakePoint(95 ,286,2),
                                            MakePoint(99 ,286,2),
                                            MakePoint(108 ,286,2),
                                            MakePoint(122 ,286,2),
                                            MakePoint(140 ,286,2),
                                            MakePoint(155 ,288,2),
                                            MakePoint(166 ,289,2),
                                            MakePoint(171 ,295,2),
                                            MakePoint(174 ,306,2),
                                            MakePoint(181 ,327,2),
                                            MakePoint(182 ,340,2),
                                            MakePoint(183 ,354,2),
                                            MakePoint(184 ,363,2),
                                            MakePoint(184 ,370,2),
                                            MakePoint(183 ,373,2),
                                            MakePoint(182 ,375,2),
                                            MakePoint(180 ,377,2),
                                            MakePoint(177 ,380,2),
                                            MakePoint(174 ,382,2),
                                            MakePoint(171 ,384,2),
                                            MakePoint(167 ,389,2),
                                            MakePoint(163 ,391,2),
                                            MakePoint(159 ,392,2),
                                            MakePoint(153 ,393,2),
                                            MakePoint(147 ,393,2),
                                            MakePoint(144 ,394,2),
                                            MakePoint(136 ,395,2),
                                            MakePoint(134 ,396,2),
                                            MakePoint(129 ,396,2),
                                            MakePoint(128 ,396,2),
                                            MakePoint(126 ,396,2),
                                            MakePoint(125 ,396,2),
                                            MakePoint(124 ,396,2),
                                            MakePoint(123 ,396,2),
                                            MakePoint(121 ,396,2),
                                            MakePoint(120 ,396,2),
                                            MakePoint(115 ,396,2),
                                            MakePoint(111 ,396,2),
                                            MakePoint(108 ,396,2),
                                            MakePoint(106 ,396,2),
                                            MakePoint(105 ,396,2),
                                            MakePoint(105 ,396,2),
                                            MakePoint(105 ,394,2),
                                            MakePoint(104 ,394,2),
                                            MakePoint(104 ,394,2),
                                            MakePoint(103 ,394,2),
                                            MakePoint(102 ,391,2),
                                            MakePoint(94 ,388,2),
                                            MakePoint(92 ,386,2),
                                            MakePoint(91 ,386,2)
                                            ]);
    
    pointClouds[12] = MakePointCloud(@"Shadow_S_Gesture", @[
                                            MakePoint(249 ,146,1),
                                            MakePoint(245 ,145,1),
                                            MakePoint(240 ,143,1),
                                            MakePoint(232 ,141,1),
                                            MakePoint(223 ,138,1),
                                            MakePoint(213 ,135,1),
                                            MakePoint(200 ,133,1),
                                            MakePoint(188 ,133,1),
                                            MakePoint(171 ,133,1),
                                            MakePoint(156 ,133,1),
                                            MakePoint(138 ,140,1),
                                            MakePoint(125 ,146,1),
                                            MakePoint(110 ,154,1),
                                            MakePoint(99 ,163,1),
                                            MakePoint(92 ,170,1),
                                            MakePoint(87 ,179,1),
                                            MakePoint(83 ,186,1),
                                            MakePoint(82 ,194,1),
                                            MakePoint(82 ,202,1),
                                            MakePoint(84 ,210,1),
                                            MakePoint(90 ,217,1),
                                            MakePoint(100 ,224,1),
                                            MakePoint(112 ,230,1),
                                            MakePoint(124 ,237,1),
                                            MakePoint(140 ,243,1),
                                            MakePoint(156 ,248,1),
                                            MakePoint(173 ,255,1),
                                            MakePoint(187 ,260,1),
                                            MakePoint(201 ,266,1),
                                            MakePoint(214 ,272,1),
                                            MakePoint(226 ,279,1),
                                            MakePoint(239 ,286,1),
                                            MakePoint(249 ,294,1),
                                            MakePoint(256 ,302,1),
                                            MakePoint(263 ,311,1),
                                            MakePoint(268 ,321,1),
                                            MakePoint(271 ,331,1),
                                            MakePoint(273 ,341,1),
                                            MakePoint(273 ,352,1),
                                            MakePoint(273 ,362,1),
                                            MakePoint(267 ,374,1),
                                            MakePoint(260 ,385,1),
                                            MakePoint(249 ,395,1),
                                            MakePoint(234 ,406,1),
                                            MakePoint(219 ,414,1),
                                            MakePoint(204 ,418,1),
                                            MakePoint(188 ,421,1),
                                            MakePoint(171 ,421,1),
                                            MakePoint(156 ,421,1),
                                            MakePoint(144 ,418,1),
                                            MakePoint(133 ,412,1),
                                            MakePoint(127 ,405,1),
                                            MakePoint(121 ,398,1),
                                            MakePoint(117 ,390,1),
                                            MakePoint(113 ,382,1),
                                            MakePoint(109 ,374,1),
                                            MakePoint(106 ,368,1),
                                            MakePoint(103 ,362,1),
                                            MakePoint(100 ,356,1),
                                            MakePoint(97 ,351,1),
                                            MakePoint(95 ,346,1),
                                            MakePoint(92 ,343,1),
                                            MakePoint(89 ,340,1),
                                            MakePoint(88 ,338,1),
                                            MakePoint(86 ,336,1),
                                            MakePoint(86 ,335,1)
                                            
                                            
                                            
                                            
                                            ]);
    
    
    pointClouds[13]= MakePointCloud(@"Paragraphstyle_J_Gesture", @[
                                                                   
                                                                   
                                                                   
                                                                MakePoint(174,90,1),
                                                                MakePoint(186,91,1),
                                                                MakePoint(205,91,1),
                                                                MakePoint(227,90,1),
                                                                MakePoint(250,86,1),
                                                                MakePoint(270,81,1),
                                                                MakePoint(285,78,1),
                                                                  MakePoint(294,77,1),
                                                                   MakePoint(300,76,1),
                                                                  MakePoint(303,76,1),
                                                                  MakePoint(301,76,1),
                                                                  MakePoint(299,76,1),
                                                                   MakePoint(297,77,1),
                                                                   MakePoint(296.,77,1),
                                                                   MakePoint(296,78,1),
                                                                   MakePoint(295,78,1),
                                                                   MakePoint(295,79,1),
                                                                   MakePoint(294,79,1),
                                                                   MakePoint(294,80,1),
                                                                   MakePoint(293,80,1),
                                                                   MakePoint (293,81,1),
                                                                   MakePoint(292,83,1),
                                                                   MakePoint(292,86,1),
                                                                   MakePoint(291,89,1),
                                                                   MakePoint(291,94,1),
                                                                   MakePoint(291,100,1),
                                                                   MakePoint(291,107,1),
                                                                   MakePoint(291,116,1),
                                                                   MakePoint(291,125,1),
                                                                   MakePoint(292,136,1),
                                                                   MakePoint(293,148,1),
                                                                   MakePoint(294,158,1),
                                                                   MakePoint(295,170,1),
                                                                   MakePoint(296,179,1),
                                                                   MakePoint(296,188,1),
                                                                   MakePoint(296,196,1),
                                                                   MakePoint(295,205,1),
                                                                   MakePoint(292,213,1),
                                                                   MakePoint(287,220,1),
                                                                   MakePoint(281,226,1),
                                                                   MakePoint(275,230,1),
                                                                   MakePoint(268,232,1),
                                                                   MakePoint(260,234,1),
                                                                   MakePoint(251,234,1),
                                                                   MakePoint(241,234,1),
                                                                   MakePoint(231,231,1),
                                                                   MakePoint(223,226,1),
                                                                   MakePoint(215,221,1),
                                                                   MakePoint(209,215,1),
                                                                   MakePoint(205,210,1),
                                                                   MakePoint(203,204,1),
                                                                   MakePoint(202,198,1),
                                                                   MakePoint(202,192,1),
                                                                   MakePoint(205,185,1),
                                                                   MakePoint(210,179,1),
                                                                   MakePoint(215,176,1),
                                                                   MakePoint(218,175,1),
                                                                   MakePoint(221,174,1),
                                                                   MakePoint(223,174,1),
                                                                   MakePoint(224,174,1),
                                                                   MakePoint(224,175,1),
                                                                   MakePoint(223,176,1),
                                                                   MakePoint(223,177,1),
                                                                   MakePoint(222,177,1),
                                                                   MakePoint(222,178,1)
                                                                                   
                                                                                   
                                                                                   
                                                                                   
                                                                                   
                                                                                   
                                                                                   ]);
    
    
    pointClouds[14] = MakePointCloud(@"Underline_U_Gesture", @[
                                                               
                                                               
                                                               MakePoint(190,85,1),
                                                               MakePoint(190,88,1),
                                                               MakePoint(191,92,1),
                                                               MakePoint(192,99,1),
                                                               MakePoint(192,105,1),
                                                               MakePoint(193,114,1),
                                                               MakePoint(194,123,1),
                                                               MakePoint(194,132,1),
                                                               MakePoint(195,140,1),
                                                               MakePoint(196,148,1),
                                                               MakePoint(198,155,1),
                                                               MakePoint(200,161,1),
                                                               MakePoint(202,165,1),
                                                               MakePoint(204,170,1),
                                                               MakePoint(206,174,1),
                                                               MakePoint(209,178,1),
                                                               MakePoint(211,181,1),
                                                               MakePoint(214,183,1),
                                                               MakePoint(218,185,1),
                                                               MakePoint(222,187,1),
                                                               MakePoint(229,189,1),
                                                               MakePoint(236,191,1),
                                                               MakePoint(241,192,1),
                                                               MakePoint(248,192,1),
                                                               MakePoint(253,192,1),
                                                               MakePoint(259,190,1),
                                                               MakePoint(264,187,1),
                                                               MakePoint(268,184,1),
                                                               MakePoint(273,182,1),
                                                               MakePoint(276,179,1),
                                                               MakePoint(280,175,1),
                                                               MakePoint(282,172,1),
                                                               MakePoint(284,167,1),
                                                               MakePoint(286,163,1),
                                                               MakePoint(287,160,1),
                                                               MakePoint(289,156,1),
                                                               MakePoint(291,151,1),
                                                               MakePoint(291,145,1),
                                                               MakePoint(292,140,1),
                                                               MakePoint(293,136,1),
                                                               MakePoint(293,130,1),
                                                               MakePoint(293,125,1),
                                                               MakePoint(293,120,1),
                                                               MakePoint(293,115,1),
                                                               MakePoint(293,111,1),
                                                               MakePoint(293,108,1),
                                                               MakePoint(293,104,1),
                                                               MakePoint(293,101,1),
                                                               MakePoint(291,98,1),
                                                               MakePoint(291,95,1),
                                                               MakePoint(290,92,1),
                                                               MakePoint(290,88,1),
                                                               MakePoint(289,85,1),
                                                               MakePoint(288,82,1),
                                                               MakePoint(288,80,1),
                                                               MakePoint(288,78,1),
                                                               MakePoint(287,76,1),
                                                               MakePoint(287,75,1),
                                                               MakePoint(287,74,1),
                                                               MakePoint(287,73,1)

                                                               
                                                               
                                                               
                                                               
                                                               
                                                               
                                                               ]);
    
    
    pointClouds[15]= MakePointCloud(@"Strikethrough_F_Gesture", @[
                                           
                                                                  
                                        
                                            
                                            
                                            
                                            
                                            MakePoint(219, 109,1),
                                            MakePoint(219, 114,1),
                                            MakePoint(220, 120,1),
                                            MakePoint(221, 128,1),
                                            MakePoint(222, 136,1),
                                            MakePoint(223, 146,1),
                                            MakePoint(223, 155,1),
                                            MakePoint(224, 166,1),
                                            MakePoint(226, 176,1),
                                            MakePoint(227, 187,1),
                                            MakePoint(229, 198,1),
                                            MakePoint(230, 209,1),
                                            MakePoint(231, 217,1),
                                            MakePoint(233, 227,1),
                                            MakePoint(235, 234,1),
                                            MakePoint(236, 239,1),
                                            MakePoint(236, 243,1),
                                            MakePoint(237, 247,1),
                                            MakePoint(238, 249,1),
                                            MakePoint(238, 248,1),
                                            MakePoint(222, 117,2),
                                            MakePoint(226, 116,2),
                                            MakePoint(231, 114,2),
                                            MakePoint(238, 112,2),
                                            MakePoint(245, 110,2),
                                            MakePoint(252, 108,2),
                                            MakePoint(259, 106,2),
                                            MakePoint(267, 105,2),
                                            MakePoint(275, 104,2),
                                            MakePoint(284, 102,2),
                                            MakePoint(292, 101,2),
                                            MakePoint(299, 100,2),
                                            MakePoint(305, 98,2),
                                            MakePoint(310, 98,2),
                                            MakePoint(314, 97,2),
                                            MakePoint(317, 96,2),
                                            MakePoint(320, 95,2),
                                            MakePoint(322, 95,2),
                                            MakePoint(323, 95,2),
                                            MakePoint(323, 96,2),
                                            MakePoint(232, 171,3),
                                            MakePoint(234, 171,3),
                                            MakePoint(237, 171,3),
                                            MakePoint(240, 171,3),
                                            MakePoint(243, 170,3),
                                            MakePoint(247, 169,3),
                                            MakePoint(250, 168,3),
                                            MakePoint(254, 168,3),
                                            MakePoint(258, 167,3),
                                            MakePoint(262, 167,3),
                                            MakePoint(266, 166,3),
                                            MakePoint(270, 166,3),
                                            MakePoint(273, 166,3),
                                            MakePoint(277, 165,3),
                                            MakePoint(281, 165,3),
                                            MakePoint(285, 164,3),
                                            MakePoint(289, 164,3),
                                            MakePoint(293, 163,3),
                                            MakePoint(298, 163,3),
                                            MakePoint(301, 162,3),
                                            MakePoint(305, 161,3),
                                            MakePoint(309, 161,3),
                                            MakePoint(312, 161,3),
                                            MakePoint(316, 160,3),
                                            MakePoint(318, 160,3),
                                            MakePoint(321, 160,3),
                                            MakePoint(324, 160,3),
                                            MakePoint(326, 159,3),
                                            MakePoint(328, 159,3),
                                            MakePoint(330, 159,3),
                                            MakePoint(332, 159,3),
                                            MakePoint(333, 159,3)
                                           
                                            ]);
    
    pointClouds[16] = MakePointCloud(@"Fontcolor_R_Gesture", @[
                                                               MakePoint(210,249,1),
                                                               MakePoint(210,247,1),
                                                               MakePoint(210,245,1),
                                                               MakePoint(210,241,1),
                                                               MakePoint(210,235,1),
                                                               MakePoint(210,228,1),
                                                               MakePoint(210,222,1),
                                                               MakePoint(210,218,1),
                                                               MakePoint(210,213,1),
                                                               MakePoint(210,207,1),
                                                               MakePoint(210,201,1),
                                                               MakePoint(210,193,1),
                                                               MakePoint(210,181,1),
                                                               MakePoint(211,173,1),
                                                               MakePoint(211,166,1),
                                                               MakePoint(211,160,1),
                                                               MakePoint(211,156,1),
                                                               MakePoint(211,152,1),
                                                               MakePoint(211,148,1),
                                                               MakePoint(211,144,1),
                                                               MakePoint(211,140,1),
                                                               MakePoint(211,136,1),
                                                               MakePoint(211,131,1),
                                                               MakePoint(212,127,1),
                                                               MakePoint(214,123,1),
                                                               MakePoint(217,119,1),
                                                               MakePoint(219,116,1),
                                                               MakePoint(222,113,1),
                                                               MakePoint(226,110,1),
                                                               MakePoint(230,106,1),
                                                               MakePoint(235,103,1),
                                                               MakePoint(239,101,1),
                                                               MakePoint(243,99,1),
                                                               MakePoint(249,97,1),
                                                               MakePoint(253,96,1),
                                                               MakePoint(257,95,1),
                                                               MakePoint(261,95,1),
                                                               MakePoint(265,94,1),
                                                               MakePoint(269,94,1),
                                                               MakePoint(273,94,1),
                                                               MakePoint(278,96,1),
                                                               MakePoint(281,99,1),
                                                               MakePoint(284,101,1),
                                                               MakePoint(286,103,1),
                                                               MakePoint(288,106,1),
                                                               MakePoint(289,109,1),
                                                               MakePoint(290,113,1),
                                                               MakePoint(291,118,1),
                                                               MakePoint(291,122,1),
                                                               MakePoint(291,127,1),
                                                               MakePoint(289,132,1),
                                                               MakePoint(287,137,1),
                                                               MakePoint(285,141,1),
                                                               MakePoint(281,145,1),
                                                               MakePoint(277,150,1),
                                                               MakePoint(272,154,1),
                                                               MakePoint(267,159,1),
                                                               MakePoint(260,164,1),
                                                               MakePoint(255,168,1),
                                                               MakePoint(248,172,1),
                                                               MakePoint(242,175,1),
                                                               MakePoint(237,178,1),
                                                               MakePoint(233,180,1),
                                                               MakePoint(230,181,1),
                                                               MakePoint(226,182,1),
                                                               MakePoint(223,183,1),
                                                               MakePoint(221,183,1),
                                                               MakePoint(219,183,1),
                                                               MakePoint(217,183,1),
                                                               MakePoint(216,183,1),
                                                               MakePoint(215,183,1),
                                                               MakePoint(214,183,1),
                                                               MakePoint(213,183,1),
                                                               MakePoint(212,183,1),
                                                               MakePoint(212,182,1),
                                                               MakePoint(213,182,1),
                                                               MakePoint(214,183,1),
                                                               MakePoint(216,184,1),
                                                               MakePoint(218,185,1),
                                                               MakePoint(221,187,1),
                                                               MakePoint(224,189,1),
                                                               MakePoint(227,190,1),
                                                               MakePoint(230,193,1),
                                                               MakePoint(233,196,1),
                                                               MakePoint(236,198,1),
                                                               MakePoint(240,201,1),
                                                               MakePoint(245,205,1),
                                                               MakePoint(251,208,1),
                                                               MakePoint(256,213,1),
                                                               MakePoint(262,217,1),
                                                               MakePoint(268,220,1),
                                                               MakePoint(274,224,1),
                                                               MakePoint(279,227,1),
                                                               MakePoint(285,230,1),
                                                               MakePoint(289,233,1),
                                                               MakePoint(294,236,1),
                                                               MakePoint(299,238,1),
                                                               MakePoint(302,240,1),
                                                               MakePoint(306,242,1),
                                                               MakePoint(310,244,1),
                                                               MakePoint(313,246,1),
                                                               MakePoint(317,248,1),
                                                               MakePoint(319,249,1),
                                                               MakePoint(321,251,1),
                                                               MakePoint(323,252,1),
                                                               MakePoint(325,253,1),
                                                               MakePoint(326,254,1),
                                                               MakePoint(327,255,1),
                                                               MakePoint(328,255,1),
                                                               MakePoint(329,255,1),
                                                               MakePoint(328,255,1)

                                                               
                                                               
                                                               ]);

    

    
    return pointClouds;
}

@end


